# Generated by Django 4.2.18 on 2026-03-15 10:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име на компютър')),
                ('mac_address', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Въведете валиден MAC адрес във формат XX:XX:XX:XX:XX:XX или XX-XX-XX-XX-XX-XX.', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')], verbose_name='MAC адрес')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Опционално: Оставете празно за стандартен локален broadcast (255.255.255.255)', null=True, verbose_name='IP / Broadcast адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавен на')),
            ],
            options={
                'verbose_name': 'Компютър',
                'verbose_name_plural': 'Компютри',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_mac', models.CharField(max_length=17, verbose_name='Целеви MAC адрес')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Време на изпращане')),
                ('status', models.CharField(choices=[('success', 'Успешно изпратен'), ('error', 'Грешка при изпращане')], default='success', max_length=10, verbose_name='Статус')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Съобщение / Детайли')),
                ('computer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.computer', verbose_name='Компютър')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Потребител')),
            ],
            options={
                'verbose_name': 'WOL Лог',
                'verbose_name_plural': 'WOL Логове',
                'ordering': ['-timestamp'],
            },
        ),
    ]
